[package]
name = "graph_matching"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
opencv = { version = "0.100", default-features = false }
pulp = "0.22.3"
euclid = "0.22"

[dev-dependencies]
testresult = "0.4"
criterion = "0.5"
sha2 = "0.10"
opencv = { version = "0.100", default-features = false, features = ["imgproc", "imgcodecs"] }

[features]
default = ["visualize"]
visualize = ["opencv/imgproc"]
opencv = ["opencv/imgproc"]
profile = ["opencv/imgcodecs"]

[[bench]]
name = "filters"
harness = false
